vacatures/backoffice/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import actions

urlpatterns = [
    url(r'^publish/(?P<slug>[a-zA-z0-9]+)/$', actions.publish, name='publish'),
    url(r'^', admin.site.urls),
]

vacatures/frontoffice/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'frontoffice'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<slug>[a-zA-z0-9\-]+)/$', views.detail, name='detail'),
]

vacatures/vacatures/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [

]

vacatures/backoffice/models.py
from __future__ import unicode_literals

from django.db import models
from autoslug import AutoSlugField
from django.template.defaultfilters import slugify
import uuid
from uuid import UUID
from backoffice.common.utils import string_to_uuid
from pprint import pprint
from backoffice.common.enumerations import JobBranches, Organisations
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class Organisation(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable = False)
    titel = models.CharField(max_length=250)
    permalink = models.SlugField(null = False, blank = False, editable=False)
    dateCreated = models.DateTimeField(auto_now=True, editable = False)
    dateUpdated = models.DateTimeField(null=True, blank=True, editable = False)
    
    def __str__(self):
        return str(self.titel)
    
    def save(self, *args, **kwargs):
        if not self.permalink:
            self.permaLink = slugify(self.titel)
        
        super(Organisation, self).save()

class UserWithOrganisation(models.Model):  
    user = models.OneToOneField(User, on_delete=models.CASCADE)  
    organisation = models.CharField(max_length=8, choices=Organisations.choices())
    
    def __str__(self):
        return str(self.organisation)

class Vacature(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable = False)
    slug = models.SlugField(null=True, blank=True, editable=False)
    permalink = models.SlugField(null = False, blank = False, editable=False)
    
    organisation = models.CharField(max_length=8, choices=Organisations.choices())

    dateCreated = models.DateTimeField(auto_now=True, editable = False)
    dateUpdated = models.DateTimeField(null=True, blank=True, editable = False)
    datePublished = models.DateTimeField(null=True, blank=True, editable = False)

    def is_published(self):
        return self.datePublished is not None
   
    def __str__(self):
        return str(self.id)
    
    def content(self):
        return VacatureContent.objects.get(pk = string_to_uuid(str(self.id)))
    
    def features(self):
        return VacatureFeatures.objects.get(pk = string_to_uuid(str(self.id)))
    
    is_published.boolean = True
    is_published.short_description = "Gepubliceerd?"

class VacatureContent(models.Model):
    titel = models.CharField(max_length=250)
    omschrijving = models.TextField()
    vacatureId = models.OneToOneField(Vacature, default=uuid.uuid4, on_delete=models.CASCADE, primary_key=True, parent_link=True)
    
    def save(self, *args, **kwargs):
        vacature = Vacature.objects.get(pk = string_to_uuid(str(self.vacatureId)))
        vacature.slug = slugify(self.titel)
        
        if not vacature.permalink:
            vacature.permalink = slugify(self.titel)
        
        vacature.save()
            
        super(VacatureContent, self).save()

class VacatureFeatures(models.Model):
    code = models.CharField(max_length=8),
    #regions =  models.CharField(max_length=10, choices=JOBBRANCHES)
    jobBranches = models.CharField(max_length=8, choices=JobBranches.choices())
    vacatureId = models.OneToOneField(Vacature, default=uuid.uuid4, on_delete=models.CASCADE, primary_key=True, parent_link=True)

vacatures/frontoffice/models.py
from __future__ import unicode_literals

import uuid

from django.db import models


class Vacature(models.Model):
    slug = models.SlugField(primary_key=True)
    titel = models.CharField(max_length=250)
    omschrijving = models.TextField()
    dateCreated = models.DateTimeField(auto_now=True, editable = False)

vacatures/backoffice/views.py
from django.shortcuts import render

# Create your views here.

vacatures/frontoffice/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from .models import Vacature
from django.views import generic

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'frontoffice/index.html'
    context_object_name = 'vacatures'

    def get_queryset(self):
        """Return the last five published vacatures."""
        return Vacature.objects.filter(
        ).order_by('-dateCreated')[:5]

def detail(request, slug):
    try:
        vacature = Vacature.objects.get(slug=slug)
    except Vacature.DoesNotExist:
        raise Http404("Vacature niet gevonden")
    return render(request, 'frontoffice/detail.html', {'vacature': vacature})

vacatures/frontoffice/templates/frontoffice/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Vacatures site{% endblock %}</title>
    
    {% block includeAtEndOfHead %}{% endblock %}
</head>

<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

vacatures/frontoffice/templates/frontoffice/detail.html
{% extends "frontoffice/base.html" %}

{% block includeAtEndOfHead %}
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'frontoffice/style.css' %}" />
{% endblock %}

{% block content %}
	{% if vacature %}
		<h1>{{ vacature.titel }}</h1>
		<p>{{ vacature.omschrijving }}</p>
	{% else %}
	    <p>Vacature niet gevonden.</p>
	{% endif %}
{% endblock %}

vacatures/frontoffice/templates/frontoffice/index.html
{% extends "frontoffice/base.html" %}

{% block includeAtEndOfHead %}
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'frontoffice/style.css' %}" />
{% endblock %}

{% block content %}
	<h1>Gevonden vacatures</h1>

	{% if vacatures %}
	    <ul>
	    {% for vacature in vacatures %}
	    	<li><a href="{% url 'frontoffice:detail' vacature.slug %}">{{ vacature.titel }}</a></li>
	    {% endfor %}
	    </ul>
	{% else %}
	    <p>Geen vacatures gevonden.</p>
	{% endif %}
{% endblock %}